public class LoqateResponseObject {

    public InputClass Input;

    public List<MatchesClass> Matches;

    public class InputClass {
        public String Address;
        public String Address1;
        public String Address2;
        public String Address3;
        public String Address4;
        public String Address5;
        public String Address6;
        public String Address7;
        public String Address8;
        public String Country;
        public String SuperAdministrativeArea;
        public String AdministrativeArea;
        public String SubAdministrativeArea;
        public String Locality;
        public String DependentLocality;
        public String DoubleDependentLocality;
        public String Thoroughfare;
        public String DependentThoroughfare;
        public String Building;
        public String Premise;
        public String SubBuilding;
        public String PostalCode;
        public String Organization;
        public String PostBox;
    }

    public class MatchesClass {
        public String AVC;
        public String AQI;
        public String Organization;
        public String SubBuilding;
        public String Premise;
        public String Building;
        public String PostBox;
        public String DependentThoroughfare;
        public String Thoroughfare;
        public String DoubleDependentLocality;
        public String DependentLocality;
        public String Locality;
        public String SubAdministrativeArea;
        public String AdministrativeArea;
        public String SuperAdministrativeArea;
        public String PostalCode;
        public String Telephone;
        public String Country;
        public String CountryName;
        public String Latitude;
        public String Longitude;
        public String GeoAccuracy;
        public String Address;
        public String Address1;
        public String Address2;
        public String Address3;
        public String Address4;
        public String Address5;
        public String Address6;
        public String Address7;
        public String Address8;
    }
}
